travis:
  secure:
    BINSTAR_TOKEN: R/fTC3GSsGhREcP43JP2xXPLT527NRDagehrTA3Gu85d1ZEEE4jNT2695WpZ5Yvf8KlQKQMLx7UZzuXxGKezz7z/pI9Lc62Cyh2VZ+Cjv7yuRuI5B9rUQFdYP0tmrvvMgxGtP5w34B8FFP5hEEWdn/SjdkG5ntLic92+9rccdct+NSow8dLZXwKf/a3oN6tgnejmDvcoKdO6u/95x3Dtf9JhpjM/F8iMbF/d69E076vGQubYQ15EhshbUqqmpybvlGJyj8Wc6gQbnAWO/qSGenCPprutMnftPesqcosujqZuM8rABTKZIjt3P1WfdDQFR6V6IVx4ndxOw47cBtsYM4QsZCxcMB0+GLiEy8sCH9UgxXAD090k4hOaJnNbyCaS8TLcDze+2TbG6NSszsF0v4P9+pn3RkaZ4bsQnQWjJ5pfajhm2HLZxC7OU9lCe2tHi0MW9nn18lK5agsBrBEULdkOxd1izCUIPyoHDbhKtQw/RD4OZooZudarv7tt9JtFWcEmVJKzx5fBoQxcdG2jLXQm51BoiSUpZJ3aHlNV19Rjxm/77qqsZzDTUVS4Vmr2ZHuvearda0TvLfPjBtStNFxVLZ+OWDSHfiUabcfN2HNLq9rfIYdh1ogaA6uACsTtX/uAdMPjhjNClKFuHDsUSi9JDmWMTCQzCEmrfMZyzbA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
